[package]
name = "bdays_reminder"
version = "0.1.0"
authors = ["micheled <me@thisisdurante.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hostname = "^0.3"
time = "^0.2"
ureq = "^1.5"
