// General
pub const DNS_CHECKER_DOMAINS: &str = "DNS_CHECKER_DOMAINS";
pub const PROGRAM_NAME: &str = "DNS_CHECKER";
// micheled_emergencies chat
pub const TELEGRAM_MICHELED_EMERGENCIES_API_KEY: &str =
    "1431628156:AAG-tb9DZDLMNn74gt-0JVFeguDgfzySKjc";
pub const TELEGRAM_MICHELED_EMERGENCIES_CHAT_ID: &str = "104361488";
pub const TELEGRAM_MICHELED_EMERGENCY_MESSAGE_PREFIX: &str = "EMERGENCY";
// micheled_alive_messages chat
pub const TELEGRAM_MICHELED_ALIVE_MESSAGES_API_KEY: &str =
    "1219926400:AAEqdCwp0qgvUBjRn7BSNI4WaLcZQQXKMnc";
pub const TELEGRAM_MICHELED_ALIVE_MESSAGES_CHAT_ID: &str = "104361488";
pub const TELEGRAM_MICHELED_ALIVE_MESSAGE_PREFIX: &str = "ALIVE_MESSAGE";
