// General
pub const DNS_CHECKER_DOMAINS: &str = "DNS_CHECKER_DOMAINS";
pub const PROGRAM_NAME: &str = "DNS_CHECKER";
// micheled_emergencies chat
pub const TELEGRAM_MICHELED_EMERGENCIES_API_KEY: &str = "TELEGRAM_MICHELED_EMERGENCIES_API_KEY";
pub const TELEGRAM_MICHELED_EMERGENCIES_CHAT_ID: &str = "TELEGRAM_MICHELED_EMERGENCIES_CHAT_ID";
// micheled_alive_messages chat
pub const TELEGRAM_MICHELED_ALIVE_MESSAGES_API_KEY: &str =
    "TELEGRAM_MICHELED_ALIVE_MESSAGES_API_KEY";
pub const TELEGRAM_MICHELED_ALIVE_MESSAGES_CHAT_ID: &str =
    "TELEGRAM_MICHELED_ALIVE_MESSAGES_CHAT_ID";
