// General
pub const BDAYS_REMINDER_PEOPLE: &str = "BDAYS_REMINDER_PEOPLE";
pub const BDAYS_REMINDER_PROGRAM_NAME: &str = "BDAYS_REMINDER";
// micheled_bdays chat
pub const TELEGRAM_MICHELED_BDAYS_API_KEY: &str = "TELEGRAM_MICHELED_BDAYS_API_KEY";
pub const TELEGRAM_MICHELED_BDAYS_CHAT_ID: &str = "TELEGRAM_MICHELED_BDAYS_CHAT_ID";
