[package]
name = "dns_checker"
version = "1.0.3"
authors = ["micheled <me@micheledurante.com>"]
edition = "2018"

[dependencies]
trust-dns-resolver = "^0.19"
ureq = "^1.5"
hostname = "^0.3"

[dev-dependencies]
mockall = "0.8.*"
